baseURL=http://localhost
spring.profiles.active=dev

# ----------------- SAFESTORAGE ----------------- #
pn.ss.gestore.disponibilita.queue.name=pn-ss-external-notification-DEV-queue
pn.ss.main.bucket.events.queue.name=pn-ss-main-bucket-events-queue
pn.ss.document.availability.timeout.millis=15000
pn.ss.document.availability.interval.millis=5000
pn.ss.sqs.lookup.interval.millis=10000
pn.ss.sqs.lookup.timeout.millis=120000

# ----------------- EXTERNAL CHANNEL ----------------- #
pn.ec.notifiche.esterne.queue.name=pn-ec-cucumber-test-queue
pn.ec.sqs.lookup.interval.millis=10000
pn.ec.sqs.lookup.timeout.millis=120000