baseURL=http://localhost
spring.profiles.active=dev

channel_sms=SMS
channel_email=EMAIL
channel_pec=PEC
channel_sercq=SERCQ
channel_paper=PAPER

# ----------------- SAFESTORAGE ----------------- #
pn.ss.availability.bucket.prefix=pn-safestorage-eu-south-1
pn.ss.gestore.disponibilita.queue.name=pn-ss-external-notification-DEV-queue
pn.ss.main.bucket.events.queue.name=pn-ss-main-bucket-events-queue
pn.ss.document.availability.timeout.millis=120000
pn.ss.document.availability.interval.millis=5000
pn.ss.sqs.lookup.interval.millis=10000
pn.ss.sqs.lookup.timeout.millis=120000

# ----------------- EXTERNAL CHANNEL ----------------- #
pn.ec.notifiche.esterne.queue.name=pn-ec-cucumber-test-queue
pn.ec.scarti-consolidatore.table.name=pn-EcScartiConsolidatore
pn.ec.richieste-metadati.table.name=pn-EcRichiesteMetadati
pn.ec.sqs.lookup.interval.millis=10000
pn.ec.sqs.lookup.timeout.millis=120000