aws.profile=dev_confinfo
aws.region=eu-south-1
pn.ss.port=8080
pn.ec.port=8080
pn.sm.port=8080
pn.pdfraster.port=8080
apiKey=apiKey-dev
apiKey_test=pn-test_api_key
clientId-unknown=pn-unknown
clientId-delivery=pn-delivery
clientId-delivery-push=pn-delivery-push
clientId-cons=pn-cons-000
clientId-test=pn-test
clientId-pn-cn=pn-cn
apiKey-pn_cn=pn-cn_api_key
apiKey-cons=apiKey-pn-cons-000
apiKey-delivery-push=apiKey-pn-delivery-push
delivery_api_key=pn-delivery_api_key
doc_type_notification_attachments=PN_NOTIFICATION_ATTACHMENTS
doc_type_legal_facts=PN_LEGAL_FACTS_ST
doc_type_dummy=PN_LEGAL_FACTS
doc_type_only_sign=PN_LEGAL_FACTS_S
doc_type_external_legal-facts=PN_EXTERNAL_LEGAL_FACTS
doc_type_aar=PN_AAR
doc_type_paper_attachment=PN_PAPER_ATTACHMENT
doc_type_clean_paper_attachment=PN_CLEAN_PAPER_ATTACHMENT
doc_type_to_raster=PN_NOTIFICATION_ATTACHMENTS
doc_type_chain_transformation=PN_CHAIN_TRANSFORMATION
doc_type_chain_transformation_2=PN_CHAIN_TRANSFORMATION_2
doc_type_chain_transformation_3=PN_CHAIN_TRANSFORMATION_3
productType_for_duplicates_check=AR
productType_not_for_duplicates_check=NP
paid_rasterization=15376371009
paid_normalization=15376371008
paid_both_transformations=15376371007
paid_none_transformations=15376371006
pec.receiver.digital.address=destinatario@certificatanoprod.notifichedigitali.it
email.receiver.digital.address=test@dev.notifichedigitali.it
sms.receiver.digital.address=+390000000000
sercq.receiver.digital.address=x-pagopa-pn-sercq:send-self:notification-already-delivered
paper.receiver.digital.address=Via Roma 1
paper.document.type.invalid=INVALID
paper.document.type.rasterization=PN_PAPER_ATTACHMENT
paper.document.type.normalization=PN_CLEAN_PAPER_ATTACHMENT
tag=global_indexed_multivalue
paper.courier1=COURIER_TEST1
paper.courier2=COURIER_TEST2

#STATE-MACHINE-TEST
status =booked
process=PEC
nextStatus=VALIDATE
process-not-valid=NotValid