pn.ss.port=8081
pn.ec.port=8080
pn.sm.port=8082
pn.pdfraster.port=8083

aws.region=us-east-1
test.aws.sqs.endpoint=http://localhost:4566
test.aws.s3.endpoint=http://localhost:4566

apiKey=apiKey-dev
apiKey_test=pn-test_api_key
clientId-unknown=pn-unknown
clientId-delivery=pn-delivery
clientId-delivery-push=pn-delivery-push
clientId-cons=pn-cons-000
clientId-test=pn-test
clientId-pn-cn=pn-cn
apiKey-pn_cn=pn-cn_api_key
apiKey-cons=apiKey-pn-cons-000
apiKey-delivery-push=apiKey-pn-delivery-push
delivery_api_key=pn-delivery_api_key
doc_type_notification_attachments=PN_NOTIFICATION_ATTACHMENTS
doc_type_legal_facts=PN_LEGAL_FACTS_ST
doc_type_dummy=PN_LEGAL_FACTS
doc_type_only_sign=PN_LEGAL_FACTS_S
doc_type_external_legal-facts=PN_EXTERNAL_LEGAL_FACTS
doc_type_aar=PN_AAR
doc_type_paper_attachment=PN_PAPER_ATTACHMENT
doc_type_clean_paper_attachment=PN_CLEAN_PAPER_ATTACHMENT
doc_type_to_raster=PN_NOTIFICATION_ATTACHMENTS
doc_type_chain_transformation=PN_CHAIN_TRANSFORMATION
doc_type_chain_transformation_2=PN_CHAIN_TRANSFORMATION_2
doc_type_chain_transformation_3=PN_CHAIN_TRANSFORMATION_3
pec.receiver.digital.address=test.m@arubapec.it
email.receiver.digital.address=test.m@arubapec.it
email.receiver.digital.address.success=success@simulator.amazonses.com
sms.receiver.digital.address=+390000000000
sercq.receiver.digital.address=x-pagopa-pn-sercq:send-self:notification-already-delivered
paper.receiver.digital.address=Via Roma 1
pn.ss.availability.bucket.name=pn-safestorage-eu-south-1
pn.ss.availability.bucket.staging.name=pn-safestorage-staging-eu-south-1
paper.document.type.invalid=INVALID
paper.document.type.rasterization=PN_PAPER_ATTACHMENT
paper.document.type.normalization=PN_CLEAN_PAPER_ATTACHMENT

tag=IUN
localTag=NrtLocalTag
indexedLocalTag=local_indexed_singlevalue
multiValueTag=global_indexed_multivalue


status =BOOKED
process=INVIO_PEC
nextStatus=VALIDATE

#IO-CONNECTOR
pn.io.port=8080
io.iun=ABCD-EFGH-1234-5678-Z
io.recipientTaxId=PF-36b40f4c-f792-40ca-9c52-a94a32b5fc28
io.recipientTaxId.blocked=BLOCKED000000000
io.recipientTaxId.notOnIo=PF-ef4f3181-c2a9-4924-9307-d107af8f0c34
io.senderServiceId=01KP5QYVRZDDEMHCN3TV1QY1H6
io.senderTaxId=12345678901
# TODO: valorizzare con la porta dell'API Gateway esterna (App IO) prima di rimuovere @wip da downloadIoAttachment.feature
pn.io.external.port=8080
